/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai3sw;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author pc
 */
public class ListView_Bai3 extends javax.swing.JFrame {

    /**
     * Creates new form ListView_Bai3
     */
    public ListView_Bai3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChuyenallsangtrai = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTrai = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPhai = new javax.swing.JList<>();
        btnChuyensangphai = new javax.swing.JButton();
        btnCongtrai = new javax.swing.JButton();
        btnChuyenallsangphai = new javax.swing.JButton();
        btnCongphai = new javax.swing.JButton();
        btnChuyensangtrai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnChuyenallsangtrai.setText("<<");
        btnChuyenallsangtrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenallsangtraiActionPerformed(evt);
            }
        });

        jLabel1.setText("DS môn thể thao");

        jLabel2.setText("Môn yêu thích");

        jScrollPane1.setViewportView(jListTrai);

        jScrollPane2.setViewportView(jListPhai);

        btnChuyensangphai.setText(">");
        btnChuyensangphai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyensangphaiActionPerformed(evt);
            }
        });

        btnCongtrai.setText("+");
        btnCongtrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongtraiActionPerformed(evt);
            }
        });

        btnChuyenallsangphai.setText(">>");
        btnChuyenallsangphai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenallsangphaiActionPerformed(evt);
            }
        });

        btnCongphai.setText("+");
        btnCongphai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongphaiActionPerformed(evt);
            }
        });

        btnChuyensangtrai.setText("<");
        btnChuyensangtrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyensangtraiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnChuyenallsangtrai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChuyenallsangphai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChuyensangphai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChuyensangtrai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCongtrai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnCongphai))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChuyensangphai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(btnChuyenallsangphai)
                        .addGap(18, 18, 18)
                        .addComponent(btnChuyensangtrai)
                        .addGap(18, 18, 18)
                        .addComponent(btnChuyenallsangtrai)
                        .addGap(10, 10, 10))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCongtrai)
                    .addComponent(btnCongphai))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChuyensangphaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyensangphaiActionPerformed
        // TODO add your handling code here:
        ListModel mTrai=jListTrai.getModel();
        ListModel mPhai=jListPhai.getModel();
        //Chuyển sang dạng ArrayList để xử
        List<String> listTrai= new ArrayList<>();
        List<String> listPhai= new ArrayList<>();
        for(int i=0;i<mTrai.getSize();i++)
            listTrai.add((String) mTrai.getElementAt(i));
        int i=jListTrai.getSelectedIndex();
        //Thêm qua listPhai
        for(int j=0;j<mPhai.getSize();j++)
            listPhai.add((String) mPhai.getElementAt(j));
        listPhai.add((String)mTrai.getElementAt(i));
        //Xóa khỏi listTrai
        listTrai.remove(i);
        
        //Chuyển list sang mảng để sử dụng
        //Phương thức setListData
        String[] arrDataTrai=listTrai.toArray(new String[0]);
        String[] arrDataPhai=listPhai.toArray(new String[0]);
        jListTrai.setListData(arrDataTrai);
        jListPhai.setListData(arrDataPhai);
        
    }//GEN-LAST:event_btnChuyensangphaiActionPerformed

    private void btnCongtraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongtraiActionPerformed
        // TODO add your handling code here:
        String sTheThao=JOptionPane.showInputDialog(this, "Nhập môn thể thao");

        //Thêm vào JListTrai
        //2.1
        ListModel mTrai=jListTrai.getModel();
        //2.2 Chuyển sang dạng ArrayList để xử
        List<String> listTrai= new ArrayList<>();
        for(int i=0;i<mTrai.getSize();i++)
            listTrai.add((String) mTrai.getElementAt(i));
        //Thêm data vừa input
        listTrai.add((sTheThao));
        //2.3 Đưa ra hiển thị
        //Chuyển list sang mảng để sử dụng
        //Phương thức setListData
        String[] arrData=listTrai.toArray(new String[0]);
        jListTrai.setListData(arrData);
    }//GEN-LAST:event_btnCongtraiActionPerformed

    private void btnCongphaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongphaiActionPerformed
        // TODO add your handling code here:
        String sMonYeuThich=JOptionPane.showInputDialog(this, "Nhập môn yêu thích");

        //Thêm vào JListPhai
        //2.1
        ListModel mPhai=jListPhai.getModel();
        //2.2 Chuyển sang dạng ArrayList để xử
        List<String> listPhai= new ArrayList<>();
        for(int i=0;i<mPhai.getSize();i++)
            listPhai.add((String) mPhai.getElementAt(i));
        //Thêm data vừa input
        listPhai.add((sMonYeuThich));
        //2.3 Đưa ra hiển thị
        //Chuyển list sang mảng để sử dụng
        //Phương thức setListData
        String[] arrData=listPhai.toArray(new String[0]);
        jListPhai.setListData(arrData);
    }//GEN-LAST:event_btnCongphaiActionPerformed

    private void btnChuyensangtraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyensangtraiActionPerformed
        // TODO add your handling code here:
        ListModel mTrai=jListTrai.getModel();
        ListModel mPhai=jListPhai.getModel();
        //Chuyển sang dạng ArrayList để xử
        List<String> listTrai= new ArrayList<>();
        List<String> listPhai= new ArrayList<>();
        for(int i=0;i<mTrai.getSize();i++)
            listTrai.add((String) mTrai.getElementAt(i));
        //Thêm qua listTrai
        for(int j=0;j<mPhai.getSize();j++)
            listPhai.add((String) mPhai.getElementAt(j));
        int j=jListPhai.getSelectedIndex();
        listTrai.add((String)mPhai.getElementAt(j));
        //Xóa khỏi listPhai
        listPhai.remove(j);
        
        //Chuyển list sang mảng để sử dụng
        //Phương thức setListData
        String[] arrDataTrai=listTrai.toArray(new String[0]);
        String[] arrDataPhai=listPhai.toArray(new String[0]);
        jListTrai.setListData(arrDataTrai);
        jListPhai.setListData(arrDataPhai);
    }//GEN-LAST:event_btnChuyensangtraiActionPerformed

    private void btnChuyenallsangphaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenallsangphaiActionPerformed
        // TODO add your handling code here:
        ListModel mTrai=jListTrai.getModel();
        ListModel mPhai=jListPhai.getModel();
        //Chuyển sang dạng ArrayList để xử
        List<String> listTrai= new ArrayList<>();
        List<String> listPhai= new ArrayList<>();
        for(int j=0;j<mPhai.getSize();j++)
            listPhai.add((String) mPhai.getElementAt(j));
        for(int i=0;i<mTrai.getSize();i++)
        {
            listTrai.add((String) mTrai.getElementAt(i));
            //Thêm qua listPhai
            listPhai.add((String) mTrai.getElementAt(i));
            
        }    
        //Xóa khỏi listTrai
            listTrai.clear();
        
        //Chuyển list sang mảng để sử dụng
        //Phương thức setListData
        String[] arrDataTrai=listTrai.toArray(new String[0]);
        String[] arrDataPhai=listPhai.toArray(new String[0]);
        jListTrai.setListData(arrDataTrai);
        jListPhai.setListData(arrDataPhai);
    }//GEN-LAST:event_btnChuyenallsangphaiActionPerformed

    private void btnChuyenallsangtraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenallsangtraiActionPerformed
        // TODO add your handling code here:
        ListModel mTrai=jListTrai.getModel();
        ListModel mPhai=jListPhai.getModel();
        //Chuyển sang dạng ArrayList để xử
        List<String> listTrai= new ArrayList<>();
        List<String> listPhai= new ArrayList<>();
        for(int j=0;j<mTrai.getSize();j++)
            listTrai.add((String) mTrai.getElementAt(j));
        for(int i=0;i<mPhai.getSize();i++)
        {
            listPhai.add((String) mPhai.getElementAt(i));
            //Thêm qua listPhai
            listTrai.add((String) mPhai.getElementAt(i));
            
        }    
        //Xóa khỏi listPhai
            listPhai.clear();
        
        //Chuyển list sang mảng để sử dụng
        //Phương thức setListData
        String[] arrDataTrai=listTrai.toArray(new String[0]);
        String[] arrDataPhai=listPhai.toArray(new String[0]);
        jListTrai.setListData(arrDataTrai);
        jListPhai.setListData(arrDataPhai);
    }//GEN-LAST:event_btnChuyenallsangtraiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListView_Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListView_Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListView_Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListView_Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListView_Bai3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyenallsangphai;
    private javax.swing.JButton btnChuyenallsangtrai;
    private javax.swing.JButton btnChuyensangphai;
    private javax.swing.JButton btnChuyensangtrai;
    private javax.swing.JButton btnCongphai;
    private javax.swing.JButton btnCongtrai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListPhai;
    private javax.swing.JList<String> jListTrai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
